GRANT ALL PRIVILEGES ON SixNations.* TO "Benjamin_Morel" WITH GRANT OPTION;

GRANT INSERT,UPDATE,DELETE ON Player TO Coach;
GRANT INSERT,UPDATE,DELETE ON Coach TO Coach;
GRANT INSERT, UPDATE, DELETE ON Positions TO Coach;
GRANT SELECT ON SixNations.* To Coach WITH GRANT OPTION;



GRANT SELECT ON SixNations.* TO Referee WITH GRANT OPTION; 
GRANT INSERT, UPDATE, DELETE ON Referee TO Referee;
GRANT INSERT, UPDATE, DELETE ON Rugby_Match TO Referee;
GRANT INSERT, UPDATE, DELETE ON Score_Details TO Referee;

GRANT INSERT, UPDATE ON Positions TO Player;

REVOKE ALL, GRANT OPTION FROM "Eddie_Jones";  



