DROP ROLE ceo, Coach, Referee, Player;
CREATE ROLE ceo, Coach, Referee, Player;

CREATE USER IF NOT EXISTS "Benjamin_Morel" DEFAULT ROLE ceo;

CREATE USER IF NOT EXISTS "Andy_Farrell" DEFAULT ROLE Coach;
CREATE USER IF NOT EXISTS "Eddie_Jones" DEFAULT ROLE Coach;
CREATE USER IF NOT EXISTS "Wayne_Pivac" DEFAULT ROLE Coach;
CREATE USER IF NOT EXISTS "Gregor_Townsend" DEFAULT ROLE Coach;
CREATE USER IF NOT EXISTS "Fabien_Galthie" DEFAULT ROLE Coach;
CREATE USER IF NOT EXISTS "Franco_Smith" DEFAULT ROLE Coach;

CREATE USER IF NOT EXISTS "Matthew_Carley" DEFAULT ROLE Referee;
CREATE USER IF NOT EXISTS "Nigel_Owens" DEFAULT ROLE Referee;
CREATE USER IF NOT EXISTS "Luke_Pearce" DEFAULT ROLE Referee;
CREATE USER IF NOT EXISTS "Pascel_Gauzere" DEFAULT ROLE Referee;
CREATE USER IF NOT EXISTS "Romain_Poite" DEFAULT ROLE Referee;